do $$
declare
  updated_count integer;
begin
  update public.legal_pages
  set title = 'Terms',
      body_jsonb = jsonb_build_array(
    'Effective Date: September 22, 2026',
    'These Terms and Conditions (“Terms”) govern your access to and use of the Becoming the Man She Can Trust website, its articles, book-related materials, frameworks, resources, communications, and other content provided through the website (collectively, the “Website”).',
    'The Website is operated by Love Purpose Flourish Inc (“Company,” “we,” “us,” or “our”). By accessing or using the Website, you agree to these Terms. If you do not agree with these Terms, do not use the Website.',
    '1. Educational and Informational Purpose',
    'The Website, Becoming the Man She Can Trust, the Love | Purpose | Flourish framework, the Twenty-Four Non-Negotiables, articles, exercises, examples, and related materials are provided for general educational, motivational, and informational purposes only.',
    'Nothing on the Website constitutes individualized medical, mental-health, psychological, therapeutic, counseling, legal, financial, or other professional advice, diagnosis, or treatment.',
    'Use of the Website does not create a therapist-client, counselor-client, physician-patient, attorney-client, fiduciary, or other professional relationship between you and Love Purpose Flourish Inc, the author, or any contributor.',
    'You remain responsible for evaluating your individual circumstances and determining whether assistance from a qualified professional is appropriate.',
    'The Website''s separate Disclaimer is incorporated into these Terms by reference and contains additional professional-scope, safety, emergency, and outcome limitations.',
    '2. Safety and Emergency Matters',
    'The Website and its materials are not emergency or crisis services.',
    'Nothing provided through the Website should be used to justify, excuse, encourage, or facilitate abuse, coercive control, stalking, manipulation, retaliation, sexual coercion, violence, threats, or other unlawful or dangerous conduct.',
    'If you or another person is experiencing immediate danger, violence, stalking, sexual assault, suicidality, a severe mental-health crisis, or another emergency, appropriate emergency services, crisis resources, law enforcement where appropriate, or qualified professional assistance should take priority over ordinary relationship guidance.',
    '3. No Guaranteed Outcomes',
    'Relationship, personal-development, communication, leadership, and behavioral information necessarily involves individual circumstances and human choices.',
    'Love Purpose Flourish Inc does not guarantee reconciliation, attraction, marriage, commitment, sexual intimacy, relationship preservation, personal transformation, financial results, professional advancement, or any other particular outcome from use of the Website, book, framework, exercises, or related materials.',
    'You remain responsible for your own decisions, conduct, relationships, boundaries, safety, and actions.',
    '4. Intellectual Property',
    'Unless otherwise stated, the Website and its original content are owned by or licensed to Love Purpose Flourish Inc and are protected by applicable copyright, trademark, and other intellectual-property laws.',
    'Protected materials may include, without limitation:',
    '• text, articles, and book excerpts;',
    '• the Love | Purpose | Flourish framework;',
    '• the Twenty-Four Non-Negotiables and related framework materials;',
    '• graphics, photographs, illustrations, audio, and video;',
    '• worksheets, exercises, downloadable materials, and educational resources;',
    '• logos, branding, trade dress, and website design; and',
    '• other original materials appearing on the Website.',
    'You may access Website content for personal, non-commercial, lawful use.',
    'Except where applicable law provides otherwise, you may not reproduce, republish, distribute, sell, license, modify, create derivative works from, publicly display, scrape for commercial exploitation, or otherwise commercially exploit protected Website content without prior written permission from Love Purpose Flourish Inc.',
    '5. Acceptable Use',
    'You agree not to:',
    '• use the Website for unlawful, fraudulent, abusive, threatening, or harmful activity;',
    '• interfere with or disrupt the Website or its infrastructure;',
    '• attempt unauthorized access to systems, accounts, data, or security controls;',
    '• introduce malware or harmful code;',
    '• impersonate another person or misrepresent your affiliation with another person or entity;',
    '• use automated systems in a manner that materially burdens, damages, or disrupts the Website;',
    '• violate another person''s intellectual-property, privacy, publicity, or other rights; or',
    '• use Website content to promote abusive, coercive, discriminatory, or unlawful conduct.',
    '6. Email Communications',
    'Joining the Website''s mailing list or community is voluntary.',
    'If you affirmatively consent to marketing communications, Love Purpose Flourish Inc may send book updates, articles, announcements, educational material, or related communications consistent with the consent presented at signup.',
    'You may unsubscribe from marketing communications using the unsubscribe mechanism provided in those communications.',
    'Collection and handling of personal information are governed by the Website''s Privacy Policy.',
    '7. Third-Party Services and Retailers',
    'The Website may contain links to third-party websites, retailers, hosting providers, email providers, analytics services, social platforms, or other external services.',
    'Book purchases may currently be completed through third-party retailers rather than directly through Love Purpose Flourish Inc.',
    'Third parties control their own availability, pricing, payment processing, fulfillment, returns, privacy practices, terms, and content.',
    'Love Purpose Flourish Inc does not control and is not responsible for the acts, omissions, policies, products, or services of independent third parties merely because the Website links to or uses those services.',
    '8. Disclaimer of Warranties',
    'To the fullest extent permitted by applicable law, the Website and its content are provided “as is” and “as available.”',
    'Love Purpose Flourish Inc makes no warranty that the Website will always be uninterrupted, error-free, secure, current, complete, or suitable for every person''s circumstances.',
    'To the extent permitted by law, we disclaim implied warranties, including warranties of merchantability, fitness for a particular purpose, title, and non-infringement.',
    'Nothing in these Terms excludes any warranty or right that applicable law does not permit to be excluded.',
    '9. Limitation of Liability',
    'To the fullest extent permitted by applicable law, Love Purpose Flourish Inc, the author, its affiliates, licensors, service providers, officers, directors, employees, agents, and representatives will not be liable for indirect, incidental, consequential, special, exemplary, or punitive damages arising from or related to:',
    '• use of or inability to use the Website;',
    '• reliance on Website content;',
    '• decisions or actions taken in response to Website materials;',
    '• relationship outcomes or emotional distress;',
    '• loss of profits, opportunities, goodwill, or data;',
    '• third-party websites, products, or services; or',
    '• unauthorized access to or alteration of information.',
    'To the fullest extent permitted by applicable law, the aggregate liability of Love Purpose Flourish Inc arising from or relating to the Website or these Terms will not exceed the greater of:',
    '• (a) the amount you paid directly to Love Purpose Flourish Inc through the Website during the twelve months preceding the event giving rise to the claim, or',
    '• (b) $100.',
    'Nothing in this section limits liability that cannot legally be excluded or limited under applicable law.',
    '10. Indemnification and Hold Harmless',
    'To the extent permitted by applicable law, you agree to defend, indemnify, and hold harmless Love Purpose Flourish Inc, the author, its affiliates, licensors, service providers, officers, directors, employees, agents, and representatives from and against third-party claims, liabilities, judgments, damages, losses, costs, and reasonable attorneys'' fees arising out of or relating to:',
    '• your unlawful or unauthorized use of the Website;',
    '• your material violation of these Terms;',
    '• your infringement or violation of another person''s rights;',
    '• content or material you submit through the Website; or',
    '• unlawful or wrongful conduct attributable to you in connection with your use of the Website.',
    'This indemnification obligation does not apply to the extent a claim results from conduct for which indemnification may not lawfully be required.',
    'Nothing in this provision waives rights or protections that cannot legally be waived.',
    '11. Informal Dispute Resolution',
    'Before filing arbitration or another formal proceeding concerning a dispute arising from these Terms or the Website, you and Love Purpose Flourish Inc agree to make a good-faith effort to resolve the matter informally.',
    'A party initiating a dispute must provide written notice describing the nature of the dispute, the relevant facts, and the requested resolution. Notices to Love Purpose Flourish Inc must be sent to info@lovepurposeflourish.com.',
    'The parties will have 30 days after receipt of the notice to attempt informal resolution before initiating arbitration, except where immediate relief is legally appropriate.',
    '12. Binding Arbitration',
    'PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING THE RIGHT TO HAVE CERTAIN DISPUTES DECIDED BY A COURT OR JURY.',
    'Except for matters expressly excluded below, any dispute, claim, or controversy arising out of or relating to these Terms, the Website, or the relationship between you and Love Purpose Flourish Inc that cannot be resolved informally will be resolved through binding individual arbitration.',
    'The arbitration will be administered by the American Arbitration Association (“AAA”) under the applicable AAA Consumer Arbitration Rules then in effect, except where those rules conflict with applicable law.',
    'The Federal Arbitration Act governs the interpretation and enforcement of this arbitration agreement to the extent applicable.',
    'Arbitration may be conducted remotely where permitted by applicable rules or otherwise at a location reasonably accessible to the parties.',
    'Nothing in this provision prevents either party from bringing an eligible individual claim in small-claims court.',
    'Either party may also seek temporary or injunctive relief from a court with appropriate jurisdiction when reasonably necessary to protect intellectual-property rights, confidential information, security, or to prevent immediate unlawful harm.',
    '13. Class Action and Representative-Action Waiver',
    'To the fullest extent permitted by applicable law, you and Love Purpose Flourish Inc agree that disputes will be resolved only on an individual basis.',
    'Neither party will seek to have a dispute heard as a class action, collective action, consolidated action, mass arbitration proceeding where individual treatment is legally required, private-attorney-general action, or other representative proceeding.',
    'The arbitrator may award relief only to the individual party seeking relief and only to the extent necessary to resolve that person''s individual claim.',
    'If applicable law prevents enforcement of a particular portion of this waiver, that portion will be treated in accordance with the severability provisions below rather than expanding the arbitrator''s authority beyond what applicable law permits.',
    '14. Arbitration Opt-Out',
    'You may opt out of the arbitration and class-action-waiver provisions by providing written notice to Love Purpose Flourish Inc within 30 days after you first become subject to these Terms.',
    'Your notice must clearly state that you are opting out of the arbitration agreement and include sufficient information to identify you and your request.',
    'Opt-out notices must be sent to info@lovepurposeflourish.com.',
    'An otherwise valid opt-out affects only the arbitration and class-action-waiver provisions. The remaining provisions of these Terms continue to apply.',
    '15. Governing Law',
    'Except to the extent federal law governs a particular issue, these Terms and disputes arising from them will be governed by the laws of the State of Georgia, without regard to conflict-of-law principles.',
    'For disputes that are not required to be arbitrated, the parties consent to jurisdiction in a court of competent jurisdiction in Georgia, subject to any venue or jurisdiction rights that applicable law does not permit the parties to waive.',
    '16. Severability',
    'If any provision of these Terms is determined to be unlawful, invalid, or unenforceable, that provision will be enforced to the maximum extent permitted by law or severed where necessary.',
    'The remaining provisions will continue in effect unless applicable law requires otherwise.',
    '17. No Waiver',
    'Failure by Love Purpose Flourish Inc to enforce a provision of these Terms does not waive the right to enforce that provision or another provision later.',
    '18. Assignment',
    'You may not assign or transfer your rights or obligations under these Terms without prior written consent where consent may lawfully be required.',
    'Love Purpose Flourish Inc may assign these Terms in connection with a merger, acquisition, corporate reorganization, sale of substantially all relevant assets, or other lawful transfer of the Website or business.',
    '19. Entire Agreement',
    'These Terms, together with the Website''s Privacy Policy and Disclaimer and any additional terms expressly presented for a particular service, constitute the agreement governing use of the Website concerning the matters they address.',
    '20. Changes to These Terms',
    'Love Purpose Flourish Inc may update these Terms as the Website, services, applicable law, or business practices change.',
    'The current version will be published on the Website with an updated effective date where appropriate.',
    'Your continued use of the Website after revised Terms become effective constitutes acceptance to the extent permitted by applicable law.',
    '21. Contact',
    'Questions, notices, or other communications concerning these Terms may be directed to:',
    'Love Purpose Flourish Inc',
    'Georgia, United States',
    'Email: info@lovepurposeflourish.com'
      ),
      is_published = true,
      updated_at = now()
  where slug = 'terms';

  get diagnostics updated_count = row_count;

  if updated_count <> 1 then
    raise exception 'Expected exactly one existing terms row; updated %', updated_count;
  end if;
end
$$;
