do $$
declare
  updated_count integer;
begin
  update public.legal_pages
  set title = 'Privacy Policy',
      body_jsonb = to_jsonb(ARRAY[
    'Effective Date: September 22, 2026',
    'This Privacy Policy explains how Love Purpose Flourish Inc (“Love Purpose Flourish,” “Company,” “we,” “us,” or “our”) collects, uses, discloses, stores, and protects personal information in connection with the Becoming the Man She Can Trust website, its mailing list, communications, and related website features (collectively, the “Website”).',
    'By using the Website or voluntarily providing information through it, you acknowledge the practices described in this Privacy Policy.',
    '1. Who Operates the Website',
    'The Website is operated by Love Purpose Flourish Inc.',
    'Privacy questions and privacy-rights requests may be directed to:',
    'Love Purpose Flourish Inc',
    'Georgia, United States',
    'Email: info@lovepurposeflourish.com',
    '2. Information You Provide Directly',
    'When you join the Becoming the Man She Can Trust community or mailing list, we may collect information that you voluntarily provide, including your first name, email address, marketing-consent choice, the version of the consent presented to you, the source of the request, and information necessary to process and document the request.',
    'If additional Website features later allow you to contact us, request a report, submit content, or otherwise provide information directly, the information collected will be limited to what is reasonably necessary for that particular purpose.',
    'Marketing consent is separate from other purposes. Providing information for a transactional, support, contact, or other non-marketing purpose does not automatically enroll you in marketing communications.',
    '3. Information Collected Automatically',
    'When you access the Website, hosting, network, and security infrastructure may process limited technical information necessary to deliver, secure, and operate the Website. Depending on the technology involved, this information may include IP address, browser or device information, request timestamps, requested pages or resources, referring information, network and security events, and similar technical information.',
    'We use this information for Website delivery, reliability, security, abuse prevention, debugging, and operational measurement.',
    'We do not intentionally use technical Website data to infer sensitive facts about your relationships, health, sexuality, finances, or other private circumstances.',
    '4. How We Use Personal Information',
    'We use personal information only for purposes reasonably connected to the context in which it was collected. These purposes may include operating the Website; processing community or mailing-list signups; maintaining subscriber and consent records; sending communications that you requested or authorized; maintaining delivery, unsubscribe, and suppression status; preventing duplicate processing; protecting the Website against misuse or unauthorized activity; diagnosing operational failures; maintaining records of consent; responding to lawful privacy requests; complying with applicable legal obligations; and improving Website reliability and usability.',
    'We do not use newsletter signup information to create psychological, medical, relationship, or other sensitive profiles about visitors.',
    '5. Email Communications and Marketing Consent',
    'Joining the mailing list is voluntary.',
    'When you affirmatively consent to marketing communications, we may use the information you provide to send book updates, articles, announcements, educational materials, community communications, or related messages within the scope of the consent presented when you subscribed.',
    'You may unsubscribe from marketing communications at any time by using the unsubscribe method included in an applicable message or by contacting us.',
    'Unsubscribing from marketing does not require you to stop using the public Website.',
    'We may retain limited suppression or consent records after an unsubscribe request when reasonably necessary to honor your preference, document the request, prevent future unauthorized marketing, maintain system integrity, resolve disputes, or comply with law.',
    '6. Service Providers and Infrastructure',
    'We use service providers to operate specific parts of the Website and mailing infrastructure.',
    'Supabase provides backend database services used to maintain subscriber, consent, request, operational, and published Website records.',
    'Resend provides email-audience and email-delivery infrastructure. Information necessary to maintain an email audience or deliver authorized communications may be transmitted to Resend.',
    'Vercel provides application hosting and related infrastructure.',
    'Cloudflare infrastructure may process network, security, routing, and request information associated with visits to the live domain.',
    'These providers process information in connection with services they provide to us. We do not authorize a service provider to use personal information supplied through the Website for purposes unrelated to providing or securing the applicable service except where independently permitted or required by law.',
    'Other providers may be added as the Website changes. This Privacy Policy will be updated where necessary to accurately describe material changes in processing.',
    '7. Analytics',
    'The Website architecture permits privacy-governed product analytics, but analytics must not receive raw email addresses, private contact-message text, assessment answers, AI conversation transcripts, authentication tokens, or payment information.',
    'If product analytics are enabled, they may process limited Website interaction and technical event data for purposes such as understanding aggregate visitor journeys, measuring Website functionality, identifying failures, and improving the user experience.',
    'We do not use analytics as a substitute for storing private relationship content.',
    '8. Cookies, Similar Technologies, and Preference Signals',
    'The Website or its infrastructure may use cookies, request identifiers, or similar technologies when necessary for security, session management, reliability, functionality, or enabled analytics.',
    'We do not currently operate the Website as an advertising network, and the verified production Website does not presently expose a behavioral-advertising integration.',
    'Where applicable law requires recognition of legally valid universal opt-out mechanisms for activities we actually conduct, we will process those signals as required.',
    '9. Sale, Sharing, and Targeted Advertising',
    'Based on the Website systems currently approved and deployed, Love Purpose Flourish Inc does not operate a business model that sells Website visitor personal information to third parties.',
    'The Website is not currently configured to disclose personal information for cross-context behavioral advertising or targeted advertising.',
    'If those practices ever materially change, we will update this Privacy Policy and implement any notice, consent, opt-out, or preference-signal mechanisms required by applicable law before relying on the changed practice.',
    '10. Sensitive Personal Information and Relationship Content',
    'The current production newsletter flow does not request private relationship conversations, medical information, mental-health information, sexual information, financial information, government identifiers, precise geolocation, or similar sensitive data.',
    'The architecture contemplates possible future assessment and AI features. Those features are not part of the currently verified production collection described by this Policy.',
    'Before any production feature begins collecting assessment answers, AI conversation content, or other sensitive relationship information, appropriate retention rules, deletion behavior, disclosures, consent controls, provider boundaries, and privacy verification must be approved and implemented.',
    'The governing privacy principle for those features is that sensitive relationship content is user data to protect, not telemetry to mine.',
    'If AI conversation storage is later introduced, raw conversation content may be persisted only under the consent rules applicable to that feature. Unconsented conversation content must not be repurposed as product analytics.',
    '11. Third-Party Websites and Retailers',
    'The Website may link to websites, retailers, social platforms, or other services that are independently operated.',
    'When you leave our Website and interact with an independent third party, including a retailer that processes a book purchase, that third party controls its own collection, payment processing, fulfillment, privacy practices, cookies, and terms.',
    'This Privacy Policy does not control the independent privacy practices of third parties merely because we link to them.',
    '12. Data Retention',
    'We retain personal information for only as long as reasonably necessary for the purpose for which it was collected and for legitimate operational, security, consent-record, dispute-resolution, suppression, and legal needs.',
    'Active subscriber information may be maintained while a mailing relationship remains active.',
    'Consent records may be retained as necessary to document whether and why communications were authorized.',
    'Unsubscribe and suppression records may be retained after other subscriber information is no longer needed when necessary to prevent future unwanted communications.',
    'Operational request and idempotency records may be retained for the period needed to prevent duplicate processing, investigate failures, or maintain system integrity.',
    'Technical infrastructure records may be retained according to the operational and security needs of the Website and the applicable service provider.',
    'We will not represent a specific retention period unless that period is actually configured and enforceable.',
    '13. Security',
    'We use technical and organizational controls intended to protect personal information against unauthorized access, disclosure, alteration, or destruction.',
    'These controls include restricted database access, row-level security where applicable, server-only privileged credentials, minimum-access principles, encrypted network transport, production access controls, and separation of sensitive information from ordinary analytics.',
    'No method of electronic transmission or storage can be guaranteed to be completely secure, and we cannot guarantee absolute security.',
    '14. Your Privacy Rights',
    'Depending on where you live and which privacy laws apply to Love Purpose Flourish Inc, you may have rights concerning your personal information.',
    'Those rights may include requesting access to personal information; obtaining information about categories, sources, purposes, or disclosures; correcting inaccurate information; requesting deletion; obtaining a portable copy where applicable; opting out of qualifying sales, sharing, targeted advertising, or certain profiling; limiting qualifying uses of sensitive personal information; withdrawing consent where processing depends on consent; appealing certain privacy-request decisions where applicable; and exercising rights without unlawful discrimination.',
    'These rights are subject to applicable exceptions and jurisdiction-specific requirements.',
    '15. How to Submit a Privacy Request',
    'You may submit a privacy request by emailing:',
    'Email: info@lovepurposeflourish.com',
    'Please identify the request as a privacy request and provide enough information for us to understand what you are requesting.',
    'We may need to verify your identity before fulfilling certain requests. Information collected for verification will be used for that purpose.',
    'Where applicable law permits use of an authorized agent, we may require appropriate proof that the agent is authorized to act for you and may require direct verification where legally permitted.',
    'If applicable law gives you a right to appeal a denied privacy request, you may submit the appeal through the same privacy contact unless another method is provided with the decision.',
    '16. Children’s Privacy',
    'The Website is intended for a general adult audience and is not directed to children under 13.',
    'We do not knowingly seek to collect personal information from children under 13 through the Website.',
    'If we obtain actual knowledge that personal information was collected from a child under 13 in circumstances covered by applicable law, we will take appropriate steps consistent with applicable law, which may include deleting the information unless legally compliant parental authorization or another applicable basis exists.',
    '17. Data Minimization and Purpose Limitation',
    'We seek to collect only information reasonably necessary for the purpose disclosed when it is collected.',
    'We do not intend to repurpose personal information for materially unrelated purposes without providing any notice or consent required by applicable law.',
    'Sensitive product features must establish their collection purpose, retention treatment, and privacy controls before production collection begins.',
    '18. Changes to This Privacy Policy',
    'We may update this Privacy Policy when the Website, our information practices, service providers, applicable law, or business operations materially change.',
    'The current version will be published on the Website with an updated effective date where appropriate.',
    'Where applicable law requires additional notice or consent before a materially different use of personal information, we will provide that notice or obtain that consent before relying on the changed practice.',
    '19. Contact',
    'Questions, privacy requests, or other communications concerning this Privacy Policy may be directed to:',
    'Love Purpose Flourish Inc',
    'Georgia, United States',
    'Email: info@lovepurposeflourish.com'
      ]::text[]),
      is_published = true,
      updated_at = now()
  where slug = 'privacy';

  get diagnostics updated_count = row_count;

  if updated_count <> 1 then
    raise exception 'Expected exactly one existing privacy row; updated %', updated_count;
  end if;
end
$$;
